color = input("Enter the color: ")
plural_noun = input("Enter plural noun: ")
celebrity = input("Enter the celebrity name: ")
print("Roses are "+color)
print(plural_noun+" are blue")
print("I love "+celebrity)